### ISSUE TITLE
Wiener classic cs team script

### ISSUE THREAD

**Issue by Xirzz** [Wiener93/ClassicTeamCS-for-Kolbot#1]
hey wiener!
 
posting here now I guess hehe. overall great job just found few small issues.

how do you make the barb bo at river without the BO.js script?? when using your script he just stays in town

also I'm getting this on the sorc whenever I ask her to kill diablo after finding the xp shrine for pala.

Error in ClassicTeamTaxi (classicteamtaxi.js line 217): Config.AutoCS is undefined

Also she will sometime miss the tp back to diablo if the paladin take it before her.

If I ask sorc and pal to just kill diablo without xp shrine everything is fine.

**Comment by Wiener93** [comment]
ye i found the errors. ill take a look later tonight and hope i can fix it in time, since ill be on vacation from tomorrow on.

**Comment by Wiener93** [comment]
updated both addresing your complains. bo barb might work now.  if not you´ll have to use the BattleOrders Script if you dont want him to not fight.

**Comment by Xirzz** [comment]
sup wiener hope youre doing good. taking a LOD pause for now but will come back to classic once my sorc is 99. I will then build a big classic cs team with your script

**Comment by Wiener93** [comment]
nice to hear. i tested some myself and got another tester. i didnt get any errors.

**Comment by Xirzz** [comment]
Hey man how you doing? Finally done with LOD stuff, its time for the classic team 🗡 

everything is fine with the script? I just run it as is?

**Comment by Wiener93** [comment]
ye mate. everything should work just fine now. bo barb works too weather you want him to fight or you dont want him to fight. lmk how its going.
