### ISSUE TITLE
Issues with 5th char joining to run andy/meph 

### ISSUE THREAD

**Issue by yopy12** [Wiener93/ClassicTeamCS-for-Kolbot#4]
So I'm wanting to get an additional sorc to join the game and run andy/meph while my cs team (sorc/2xdin/barb) go about the CS script. My issue is that the sorc joins and does her thing, but the CS team (barb/2x pallys) will not take the CS sorc's tp and give/get bo to start the CS run. If the andy/meph sorc leaves game, then they will perform the BO sequence and CS script runs fine.

This happens when the andy/meph sorc is either in the party with them, or isn't partied with them. I'm thinking the barb/pallys recognize an additional char in game and won't take CS sorc's tp when this is the case... 

Thoughts?

**Comment by Wiener93** [comment]
yeah mate thats because your mf sorc has a higher lvl than your taxi sorc. i ran into this Problem myself several times. if your sorc isnt meph fk you could swap the sorcs out. taxi sorc is detected as highest Level sorc. ill check if i can Change that to first sorc in area, but i cant promise.
